# Generated by Django 4.1 on 2023-02-27 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BulbType',
            fields=[
                ('buld_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('bulb_type_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bulb',
            fields=[
                ('bulb_id', models.AutoField(primary_key=True, serialize=False)),
                ('bulb_name', models.CharField(max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=50, null=True)),
                ('bulb_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lights.bulbtype')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lights.room')),
            ],
        ),
    ]
